package com.organization.sjhg.e_school.Remote;

public enum RemoteCalls {
    GET_ACTIVE_SESSIONS,
    GET_CURRENT_SESSION,
    GET_STUDENT_SESSION_STATUS,
    UPDATE_STUDENT_SESSION_STATUS,
    UPDATE_RAISE_HAND_STATUS,
    SEND_STUDENT_QUESTION,
    SEND_BATTERY_STATUS,
    SEND_RUNNING_TASKS,
    GET_SERVER_TEST_LIST,
    GET_SERVER_LAUGHGURU_LIST,
    GET_SERVER_CONTENT_LIST,
    GET_NOTES,
    GET_SUBSCRIPTION_SUBJECT_LIST,
    UPDATE_STUDENT_SUBSCRIBED_SUBJECTS,
    GET_EVENT_DETAILS,
    GET_ADAPTIVE_CONTENT,
    UPLOAD_ADAPTIVE_TEST,
    UPLOAD_LIVE_VOTING_ANSWER,
    CHECK_REMOTE_CALL,
    ////////////////////////////////////////////////////////////
    CHECK_LOGIN_CREDENTIALS,
    GET_ACCESS_TOKEN,
    GET_USER_DETAILS,
    GET_GOOGLE_USER_DETAILS,
    SIGN_UP,
    GET_ITEM_DETAILS,
    GET_DASHBOARD_LIST,
    GET_EXAM_PREPARE_LIST
}